version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      APP_DEBUG: "true"
      APP_ENV: "dev"
      APP_KEY: "base64:DJYTvaRkEZ/YcQsX3TMpB0iCjgme2rhlIOus9A1hnj4="
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: app_database
      DB_USERNAME: app_user
      DB_PASSWORD: app_password
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-1
        awslogs-group: iaas-backend-log-group
        awslogs-create-group: "true"
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: app_database
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_ROOT_PASSWORD: app_root_password
    volumes:
      - db_data:/var/lib/mysql
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-1
        awslogs-group: iaas-db-log-group
        awslogs-create-group: "true"
volumes:
  db_data:
